services:
  docmost:
    build: .
    depends_on:
      - redis
    env_file:
      - .env
    ports:
      - "3001:3000"
    restart: unless-stopped
    network_mode: host
    volumes:
      - docmost:/app/data/storage
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes", "--maxmemory-policy", "noeviction"]
    restart: unless-stopped
    network_mode: host
    volumes:
      - redis_data:/data

volumes:
  docmost:
  redis_data:
